# Project Information
site_name: NannaU CS 生存指南
site_description: NannaU CS Wiki 维护了南京大学计算机本科的一些资料
site_author: NannaU CS Group

repo_name: 'NannaU-CS/nannau-cs.github.io'
repo_url: 'https://github.com/NannaU-CS/nannau-cs.github.io'
edit_uri: 'edit/main/docs'

nav:
- 简介:
  - index.md
  - 贡献指南: intro/contributing.md
- 选课指南:
  - 前言: courses/preface.md
  - 评价指南: courses/how-to-comment.md
  - Rust程序设计语言:
    - 冯洋,徐宝文: courses/Rust程序设计语言/冯洋,徐宝文.md
  - 人工智能:
    - 杨育彬: courses/人工智能/杨育彬.md
    - 霍静,高阳: courses/人工智能/霍静,高阳.md
  - 人机接口技术:
    - 王崇骏: courses/人机接口技术/王崇骏.md
  - 信息与计算科学导论:
    - 仲盛,张渊: courses/信息与计算科学导论/仲盛,张渊.md
  - 信息与计算科学导论实验:
    - 仝伟: courses/信息与计算科学导论实验/仝伟.md
  - 信息科学与实践:
    - 赵建华: courses/信息科学与实践/赵建华.md
  - 信息论基础:
    - 姚鹏晖: courses/信息论基础/姚鹏晖.md
  - 分布式与并行计算:
    - 谢磊: courses/分布式与并行计算/谢磊.md
  - 分布式数据处理:
    - 叶保留,陆桑璐: courses/分布式数据处理/叶保留,陆桑璐.md
  - 分布式网络:
    - 陈贵海: courses/分布式网络/陈贵海.md
  - 图形绘制技术:
    - 过洁: courses/图形绘制技术/过洁.md
  - 图论与算法:
    - 程龚: courses/图论与算法/程龚.md
  - 基于强化学习的无人机群体智能导论:
    - 汪亮,陶先平: courses/基于强化学习的无人机群体智能导论/汪亮,陶先平.md
  - 多媒体技术:
    - 唐杰: courses/多媒体技术/唐杰.md
  - 大学物理:
    - 郭亚冲: courses/大学物理/郭亚冲.md
  - 大学物理实验（一）:
    - 万建国,吴雪炜,周惠君,张志勇,李世民,江洪建,游彪,潘永华,王寅龙,郑之明,高惠滨,龚国斌: courses/大学物理实验（一）/万建国,吴雪炜,周惠君,张志勇,李世民,江洪建,游彪,潘永华,王寅龙,郑之明,高惠滨,龚国斌.md
    - 万建国,周惠君,李世民,江洪建,游彪,潘永华,王寅龙,郑之明,高惠滨,龚国斌: courses/大学物理实验（一）/万建国,周惠君,李世民,江洪建,游彪,潘永华,王寅龙,郑之明,高惠滨,龚国斌.md
  - 大数据处理综合实验:
    - 余萍: courses/大数据处理综合实验/余萍.md
    - 朱光辉,黄宜华: courses/大数据处理综合实验/朱光辉,黄宜华.md
    - 顾荣: courses/大数据处理综合实验/顾荣.md
  - 学术文献阅读与写作:
    - 仲盛,张胜,程龚,钱柱中: courses/学术文献阅读与写作/仲盛,张胜,程龚,钱柱中.md
    - 张胜,王楚豫,程龚,钱柱中: courses/学术文献阅读与写作/张胜,王楚豫,程龚,钱柱中.md
  - 密码学原理:
    - 张渊: courses/密码学原理/张渊.md
  - 嵌入式系统:
    - 陈鑫: courses/嵌入式系统/陈鑫.md
  - 并行程序设计实验:
    - 卢红敏: courses/并行程序设计实验/卢红敏.md
  - 形式语言与自动机:
    - 卜磊,李宣东: courses/形式语言与自动机/卜磊,李宣东.md
  - 微积分I(第一层次):
    - 周国飞: courses/微积分I(第一层次)/周国飞.md
    - 陆宏: courses/微积分I(第一层次)/陆宏.md
  - 微积分II(第一层次):
    - 周国飞: courses/微积分II(第一层次)/周国飞.md
    - 赵秋兰: courses/微积分II(第一层次)/赵秋兰.md
    - 钱志: courses/微积分II(第一层次)/钱志.md
  - 控制理论与方法:
    - 章宗长: courses/控制理论与方法/章宗长.md
  - 操作系统:
    - 华景煜: courses/操作系统/华景煜.md
    - 叶保留: courses/操作系统/叶保留.md
    - 吴化尧: courses/操作系统/吴化尧.md
    - 徐锋: courses/操作系统/徐锋.md
    - 蒋炎岩: courses/操作系统/蒋炎岩.md
  - 数字逻辑与计算机组成:
    - 吴海军: courses/数字逻辑与计算机组成/吴海军.md
    - 周嵩: courses/数字逻辑与计算机组成/周嵩.md
    - 李俊: courses/数字逻辑与计算机组成/李俊.md
    - 杨若瑜: courses/数字逻辑与计算机组成/杨若瑜.md
  - 数字逻辑与计算机组成实验:
    - 吴海军: courses/数字逻辑与计算机组成实验/吴海军.md
    - 吴海军,周嵩: courses/数字逻辑与计算机组成实验/吴海军,周嵩.md
    - 李婷,王炜: courses/数字逻辑与计算机组成实验/李婷,王炜.md
    - 王炜: courses/数字逻辑与计算机组成实验/王炜.md
  - 数学分析（一）:
    - 范红军: courses/数学分析（一）/范红军.md
  - 数学分析（二）:
    - 卓汉逵,范红军: courses/数学分析（二）/卓汉逵,范红军.md
    - 范红军: courses/数学分析（二）/范红军.md
  - 数据库概论:
    - 张剡: courses/数据库概论/张剡.md
    - 柏文阳: courses/数据库概论/柏文阳.md
    - 胡伟: courses/数据库概论/胡伟.md
  - 数据挖掘导论:
    - TINGKAIMING: courses/数据挖掘导论/TINGKAIMING.md
  - 数据结构:
    - 刘佳: courses/数据结构/刘佳.md
    - 商琳: courses/数据结构/商琳.md
    - 姜远,时清凯: courses/数据结构/姜远,时清凯.md
    - 李武军,王楚豫: courses/数据结构/李武军,王楚豫.md
    - 王楚豫,许蕾: courses/数据结构/王楚豫,许蕾.md
    - 许蕾: courses/数据结构/许蕾.md
    - 赵建华: courses/数据结构/赵建华.md
  - 数据通信:
    - 王晓亮: courses/数据通信/王晓亮.md
  - 数理逻辑:
    - 秦逸: courses/数理逻辑/秦逸.md
  - 普通物理（上）:
    - 于葛亮: courses/普通物理（上）/于葛亮.md
    - 张建: courses/普通物理（上）/张建.md
  - 智能应用开发:
    - 徐经纬: courses/智能应用开发/徐经纬.md
    - 徐经纬,曹春: courses/智能应用开发/徐经纬,曹春.md
  - 智能计算系统:
    - 朱光辉: courses/智能计算系统/朱光辉.md
  - 智能软件工程导论:
    - 姚远,马晓星: courses/智能软件工程导论/姚远,马晓星.md
  - 最优化方法导论:
    - 张利军: courses/最优化方法导论/张利军.md
  - 机器学习导论:
    - 叶翰嘉: courses/机器学习导论/叶翰嘉.md
  - 机器学习新进展:
    - 李文斌,霍静: courses/机器学习新进展/李文斌,霍静.md
  - 机器翻译和自然语言生成:
    - 黄书剑: courses/机器翻译和自然语言生成/黄书剑.md
  - 概率论与数理统计:
    - 傅冬生: courses/概率论与数理统计/傅冬生.md
    - 陶敏: courses/概率论与数理统计/陶敏.md
  - 物联网技术导论:
    - 谢磊: courses/物联网技术导论/谢磊.md
  - 离散数学:
    - 仲盛,姚鹏晖,张渊: courses/离散数学/仲盛,姚鹏晖,张渊.md
    - 史颖欢: courses/离散数学/史颖欢.md
    - 吴楠: courses/离散数学/吴楠.md
    - 姚远: courses/离散数学/姚远.md
    - 瞿裕忠: courses/离散数学/瞿裕忠.md
    - 黄棱潇: courses/离散数学/黄棱潇.md
  - 程序设计基础:
    - 刘奇志: courses/程序设计基础/刘奇志.md
    - 孙泽群: courses/程序设计基础/孙泽群.md
    - 李元琪,过洁: courses/程序设计基础/李元琪,过洁.md
    - 过洁: courses/程序设计基础/过洁.md
    - 郭延文: courses/程序设计基础/郭延文.md
    - 黄书剑: courses/程序设计基础/黄书剑.md
  - 程序设计语言的形式语义:
    - 梁红瑾: courses/程序设计语言的形式语义/梁红瑾.md
  - 程序设计语言的解释器与虚拟机:
    - 时清凯: courses/程序设计语言的解释器与虚拟机/时清凯.md
  - 算法设计与分析:
    - 张胜: courses/算法设计与分析/张胜.md
    - 徐经纬: courses/算法设计与分析/徐经纬.md
    - 栗师: courses/算法设计与分析/栗师.md
    - 赵建华,郑朝栋: courses/算法设计与分析/赵建华,郑朝栋.md
    - 郑朝栋: courses/算法设计与分析/郑朝栋.md
    - 黄宇: courses/算法设计与分析/黄宇.md
  - 线性代数(第一层次):
    - 曹立元: courses/线性代数(第一层次)/曹立元.md
    - 汪正方: courses/线性代数(第一层次)/汪正方.md
    - 陈秦波: courses/线性代数(第一层次)/陈秦波.md
  - 组合数学:
    - 尹一通: courses/组合数学/尹一通.md
  - 编码理论:
    - 林冰凯: courses/编码理论/林冰凯.md
  - 编译原理:
    - 冯洋: courses/编译原理/冯洋.md
    - 冯洋,徐宝文: courses/编译原理/冯洋,徐宝文.md
    - 许畅: courses/编译原理/许畅.md
    - 谭添: courses/编译原理/谭添.md
    - 陈林: courses/编译原理/陈林.md
  - 网络安全与检测技术:
    - 仝伟: courses/网络安全与检测技术/仝伟.md
  - 网络安全实验:
    - 吴迎红: courses/网络安全实验/吴迎红.md
  - 网络应用开发技术:
    - 卢红敏: courses/网络应用开发技术/卢红敏.md
  - 网络攻防实战:
    - 陈健: courses/网络攻防实战/陈健.md
  - 网络空间安全与隐私保护:
    - 吴昊,许封元: courses/网络空间安全与隐私保护/吴昊,许封元.md
  - 自主移动机器人导论:
    - 陈力军: courses/自主移动机器人导论/陈力军.md
  - 计算复杂性:
    - 姚鹏晖: courses/计算复杂性/姚鹏晖.md
  - 计算方法:
    - 刘景铖: courses/计算方法/刘景铖.md
    - 李元琪,过洁: courses/计算方法/李元琪,过洁.md
  - 计算机体系结构:
    - 王炜: courses/计算机体系结构/王炜.md
  - 计算机图形学:
    - 孙正兴: courses/计算机图形学/孙正兴.md
    - 孙正兴,张岩: courses/计算机图形学/孙正兴,张岩.md
  - 计算机数学建模:
    - 周毓明: courses/计算机数学建模/周毓明.md
  - 计算机程序的构造和解释:
    - 冯新宇,李樾: courses/计算机程序的构造和解释/冯新宇,李樾.md
  - 计算机程序设计语言:
    - 张天: courses/计算机程序设计语言/张天.md
  - 计算机系统基础:
    - 刘杰,唐杰: courses/计算机系统基础/刘杰,唐杰.md
    - 唐杰,汪亮,苏丰: courses/计算机系统基础/唐杰,汪亮,苏丰.md
    - 戴海鹏,汪亮: courses/计算机系统基础/戴海鹏,汪亮.md
    - 汪亮,苏丰: courses/计算机系统基础/汪亮,苏丰.md
  - 计算机系统设计综合实验:
    - 仲盛,华景煜,吴昊: courses/计算机系统设计综合实验/仲盛,华景煜,吴昊.md
  - 计算机网络:
    - 张渊: courses/计算机网络/张渊.md
    - 李文中: courses/计算机网络/李文中.md
    - 田臣: courses/计算机网络/田臣.md
    - 郑嘉琦: courses/计算机网络/郑嘉琦.md
    - 黄程远: courses/计算机网络/黄程远.md
  - 计算机网络协议开发:
    - 曹培睿: courses/计算机网络协议开发/曹培睿.md
    - 陈健: courses/计算机网络协议开发/陈健.md
  - 计算机视觉表征与识别:
    - 王利民: courses/计算机视觉表征与识别/王利民.md
  - 软件产业概论:
    - 谢俊元: courses/软件产业概论/谢俊元.md
  - 软件体系结构:
    - 曹春: courses/软件体系结构/曹春.md
  - 软件分析:
    - 李樾,谭添: courses/软件分析/李樾,谭添.md
  - 软件安全:
    - 茅兵: courses/软件安全/茅兵.md
  - 软件工程:
    - 张天,李宣东,王林章,王豫: courses/软件工程/张天,李宣东,王林章,王豫.md
  - 软件工程综合实验:
    - 张天,曹春,王林章,王豫: courses/软件工程综合实验/张天,曹春,王林章,王豫.md
    - 张天,王林章,王豫: courses/软件工程综合实验/张天,王林章,王豫.md
  - 软件测试:
    - 吴化尧,聂长海: courses/软件测试/吴化尧,聂长海.md
  - 软件质量保障:
    - 吴化尧,聂长海: courses/软件质量保障/吴化尧,聂长海.md
  - 问题求解（一）:
    - 吕建,陶先平,马骏: courses/问题求解（一）/吕建,陶先平,马骏.md
    - 陶先平,马骏: courses/问题求解（一）/陶先平,马骏.md
  - 面向对象设计方法:
    - 霍静: courses/面向对象设计方法/霍静.md
  - 面向计算思维的问题求解:
    - 张胜,陆桑璐: courses/面向计算思维的问题求解/张胜,陆桑璐.md
  - 高等代数（一）:
    - 申富饶: courses/高等代数（一）/申富饶.md
  - 高等代数（二）:
    - 刘达欣: courses/高等代数（二）/刘达欣.md
    - 徐百乐,申富饶: courses/高等代数（二）/徐百乐,申富饶.md
  - 高级Java程序设计:
    - 曹春: courses/高级Java程序设计/曹春.md
  - 高级程序设计:
    - 左志强,徐经纬,杨已彪: courses/高级程序设计/左志强,徐经纬,杨已彪.md
    - 左志强,王豫: courses/高级程序设计/左志强,王豫.md
    - 徐经纬: courses/高级程序设计/徐经纬.md
    - 王豫,陈家骏: courses/高级程序设计/王豫,陈家骏.md
  - 高级算法:
    - 刘景铖,尹一通,栗师: courses/高级算法/刘景铖,尹一通,栗师.md
- 人生指南:
  - 保研:
    - 简介: life/baoyan/index.md
  - 考研:
    - 简介: life/caoyan/index.md
  - 出国:
    - 简介: life/abroad/index.md
  - 就业:
    - 简介: life/employment/index.md
  - 考公:
    - 简介: life/kaogong/index.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.edit
  language: 'zh'
  custom_dir: overrides


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
